### PR TITLE
merge the latest state from upstream

### PR DESCRIPTION
**Pull request by dirk-thomas**
Pulling in over a year of bug fixes and improvements.

### CODE REVIEW

**Comment by clalancette** [comment]
I'm just doing skimming of the various PRs here to make sure there is nothing obviously wrong, and approving the ones I can.  It would be good to see the green CI job.

**Comment by dirk-thomas** [comment]
And here are the links to finally finished CI builds:

* Linux [Build Status](http://ci.ros2.org/job/ci_linux/3284/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/559/)
* macOS [Build Status](http://ci.ros2.org/job/ci_osx/2615/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/3322/)

Ready for review.

**Review by clalancette — APPROVED** [review]
I'm not going to review all of the changes to uncrustify itself.  The update looks OK, and with a green CI, I'm fine with the updates.

**Comment by dirk-thomas** [comment]
And as a follow up the newly referenced PRs remove plenty of `INDENT-OFF` usage where it isn't necessary anymore or was easy to make the code comply:

* Linux [Build Status](http://ci.ros2.org/job/ci_linux/3290/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/565/)
* macOS [Build Status](http://ci.ros2.org/job/ci_osx/2626/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/3333/)

Please review the newly referenced PR.

**Comment by mikaelarguedas** [comment]
all referenced changes look good to me once ci comes back green

**Pull request merged**
