### PR TITLE
sync upstream

### PR DESCRIPTION
**Pull request by dirk-thomas**
Addressing failing tests in uncrustify itself.

http://ci.ros2.org/job/ci_linux/1674/

Please review.

### CODE REVIEW

**Comment by dirk-thomas** [comment]
Waiting for review.

**Comment by dirk-thomas** [comment]
Waiting for review.

**Comment by tfoote** [comment]
Looks reasonable.

**Comment by gerkey** [comment]
+1

As an aside, I can't believe that uncrustify is written in C++.

**Pull request merged**
